"use client";

import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Zap } from "lucide-react";

interface AIInsight {
  market_bias?: string;
  action_items?: string[];
  risk_factors?: string;
  confidence_score?: number;
  key_takeaways?: string[];
}

interface AIInsightsProps {
  aiAnalysis: AIInsight;
}

export function AIInsights({ aiAnalysis }: AIInsightsProps) {
  if (!aiAnalysis) return null;

  return (
    <Card className="border-purple-200 dark:border-purple-800 bg-gradient-to-br from-purple-50 to-blue-50 dark:from-purple-950 dark:to-blue-950">
      <div className="p-4 space-y-4">
        {/* Header */}
        <div className="flex items-center gap-2 mb-3">
          <Zap className="w-5 h-5 text-purple-600 dark:text-purple-400" />
          <h3 className="font-semibold text-purple-900 dark:text-purple-100">
            Gemini AI Insights
          </h3>
          <Badge variant="secondary" className="ml-auto">
            AI Powered
          </Badge>
        </div>

        {/* Market Bias */}
        {aiAnalysis.market_bias && (
          <div className="space-y-2">
            <h4 className="font-semibold text-sm text-purple-800 dark:text-purple-200">
              📊 Market Bias
            </h4>
            <p className="text-sm text-purple-700 dark:text-purple-300 leading-relaxed">
              {aiAnalysis.market_bias}
            </p>
          </div>
        )}

        {/* Confidence Score */}
        {aiAnalysis.confidence_score !== undefined && (
          <div className="flex items-center gap-2">
            <span className="text-sm font-medium text-purple-800 dark:text-purple-200">
              Confidence:
            </span>
            <div className="flex-1 h-2 bg-purple-200 dark:bg-purple-800 rounded-full overflow-hidden">
              <div
                className="h-full bg-gradient-to-r from-purple-500 to-blue-500 transition-all"
                style={{
                  width: `${Math.min(100, Math.max(0, aiAnalysis.confidence_score))}%`,
                }}
              />
            </div>
            <span className="text-sm font-semibold text-purple-800 dark:text-purple-200">
              {Math.round(aiAnalysis.confidence_score || 0)}%
            </span>
          </div>
        )}

        {/* Action Items */}
        {aiAnalysis.action_items && aiAnalysis.action_items.length > 0 && (
          <div className="space-y-2">
            <h4 className="font-semibold text-sm text-blue-800 dark:text-blue-200">
              🎯 Action Items
            </h4>
            <ul className="space-y-1">
              {aiAnalysis.action_items.map((item, i) => (
                <li
                  key={i}
                  className="flex gap-2 text-sm text-blue-700 dark:text-blue-300"
                >
                  <span className="font-bold text-blue-500 dark:text-blue-400">
                    •
                  </span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Key Takeaways */}
        {aiAnalysis.key_takeaways && aiAnalysis.key_takeaways.length > 0 && (
          <div className="space-y-2">
            <h4 className="font-semibold text-sm text-blue-800 dark:text-blue-200">
              💡 Key Takeaways
            </h4>
            <ul className="space-y-1">
              {aiAnalysis.key_takeaways.map((takeaway, i) => (
                <li
                  key={i}
                  className="flex gap-2 text-sm text-blue-700 dark:text-blue-300"
                >
                  <span className="font-bold text-blue-500 dark:text-blue-400">
                    →
                  </span>
                  <span>{takeaway}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {/* Risk Factors */}
        {aiAnalysis.risk_factors && (
          <div className="space-y-2 p-3 bg-red-100 dark:bg-red-900/20 rounded-lg border border-red-200 dark:border-red-800">
            <h4 className="font-semibold text-sm text-red-800 dark:text-red-200">
              ⚠️ Risk Factors
            </h4>
            <p className="text-sm text-red-700 dark:text-red-300 leading-relaxed">
              {aiAnalysis.risk_factors}
            </p>
          </div>
        )}

        {/* Footer Note */}
        <div className="text-xs text-muted-foreground pt-2 border-t border-purple-200 dark:border-purple-800">
          <p>
            AI insights generated by Gemini. Review all analysis and conduct
            your own due diligence before making decisions.
          </p>
        </div>
      </div>
    </Card>
  );
}
